# Generated by Django 4.2.1 on 2023-05-11 14:13

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.CharField(blank=True, max_length=999)),
                ('desc', models.CharField(blank=True, max_length=999)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.CharField(blank=True, max_length=999)),
                ('Bacon', models.BooleanField(default=False)),
                ('Chicken', models.BooleanField(default=False)),
                ('Ham', models.BooleanField(default=False)),
                ('Pepperoni', models.BooleanField(default=False)),
                ('Jalapeno', models.BooleanField(default=False)),
                ('Mushrooms', models.BooleanField(default=False)),
                ('Onion', models.BooleanField(default=False)),
                ('Paprika', models.BooleanField(default=False)),
                ('Pineapple', models.BooleanField(default=False)),
                ('Cheese', models.BooleanField(default=False)),
                ('Mozzarella', models.BooleanField(default=False)),
                ('Pepper_Cheese', models.BooleanField(default=False)),
                ('Yellow_Cheese', models.BooleanField(default=False)),
                ('Pizza_Sauce', models.BooleanField(default=False)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Side',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.CharField(blank=True, max_length=999)),
                ('desc', models.CharField(blank=True, max_length=999)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Phone_Number', models.IntegerField()),
                ('Profile_picture', models.CharField(max_length=9999)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pizza')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
